name: Build Documentation
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'
    workflow_dispatch:

permissions:
  contents: write            

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Restore dotnet tools
              run: dotnet tool restore

            - name: Run Build
              run: dotnet docfx docfx.all.json

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: _site
                clean: true